name: main

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  publish:
    name: NPM Publish
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 13.x
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx tsc

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public --ignore-scripts
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
